<<<<<<< HEAD
=======
version: "3.8"

>>>>>>> e9c958e10d3e740441f383396b2cad86c72c6a2e
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK}

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
      - DB_HOST=${DATABASE_HOST}
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    expose:
      - "${BACKEND_PORT}"
    networks:
      - ${NETWORK}

  frontend:
    build: ./frontend
    restart: always
    networks:
      - ${NETWORK}

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
    networks:
      - ${NETWORK}

volumes:
  db_data:

networks:
  ${NETWORK}:
    driver: bridge
