services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - myapp_network

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
      - DB_HOST=${DATABASE_HOST}
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    expose:
      - "${BACKEND_PORT}"
    networks:
      - myapp_network

  frontend:
    build: ./frontend
    restart: always
    networks:
      - myapp_network

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/dist
    depends_on:
      - frontend
      - backend
    networks:
      - myapp_network

volumes:
  db_data:

networks:
  myapp_network:
    driver: bridge
